### ISSUE TITLE
Phaser3 please

### ISSUE THREAD

**Issue by jcyuan** [kestrelm/Creature_WebGL#13]
this is really good and worth to have a try.
is there any plan to integrate with Phaser3 which is actually better then Phaser2?
there should be a CreatureDisplayRenderer.js & CreaturePlugin.js.

**Comment by jcyuan** [comment]
or if wasm available for Phaser3 too that will be fantastic!

**Comment by kestrelm** [comment]
Phaser 3 does not yet support indices on meshes:
https://github.com/photonstorm/phaser/issues/3203

This feature is required for proper mesh deformation support which Creature needs. If you can let the owner of Phaser 3 know about this or get somebody else to help out put this feature in, then it will be possible to port the Creature runtimes over.

Thanks

**Comment by jcyuan** [comment]
ok, thanks, will wait for it.

**Comment by kestrelm** [comment]
Phaser 3 CreaturePack support has just been checked in:
https://github.com/kestrelm/Creature_WebGL/tree/master/Phaser3
