### ISSUE TITLE
Doesn't work for Phaser 3.5

### ISSUE THREAD

**Issue by diruuu** [kestrelm/Creature_WebGL#15]
Is there a chance for this library to get updated for Phaser 3.5? Phaser 3.5 has different API with  Phaser  < 3.5. I tried to do that but didn't succeed.

**Comment by kestrelm** [comment]
Hello can you please post the stack trace/error from the browser console? Thanks

**Comment by diruuu** [comment]
Sure. I got this

```
phaser-arcade-physics.js:44495 Texture.frame missing: 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.....

CreaturePackPhaser3Obj.js:109 Uncaught TypeError: Cannot set property '0' of undefined
    at CreaturePackObj.preUpdate (CreaturePackPhaser3Obj.js:109)
    at UpdateList.sceneUpdate (phaser-arcade-physics.js:159964)
    at EventEmitter.emit (phaser-arcade-physics.js:1928)
    at Systems.step (phaser-arcade-physics.js:43779)
    at SceneManager.update (phaser-arcade-physics.js:94131)
    at Game.step (phaser-arcade-physics.js:154229)
    at TimeStep.step (phaser-arcade-physics.js:83210)
    at step (phaser-arcade-physics.js:83457)
```
I think this is because in Phaser 3.5, the Mesh constructor has changed to this:
```
new Mesh(scene [, x] [, y] [, texture] [, frame] [, vertices] [, uvs] [, indicies] [, containsZ] [, normals] [, colors] [, alphas])
```

It's quite different with the implementation on CreaturePackPhaser3Obj.js


# How to reproduce this issue:
Change this line on `Phaser3/Phaser3BasicSample.html` from this
```
<script src="https://cdn.jsdelivr.net/npm/phaser@3.15.1/dist/phaser-arcade-physics.js"></script>
```

To this:
```
<script src="https://cdn.jsdelivr.net/npm/phaser@3.52.0/dist/phaser-arcade-physics.js"></script>
```

**Comment by kestrelm** [comment]
Hello,

I took some time to see if I could figure it out and made a new **Phaser 3.5** branch here:
https://github.com/kestrelm/Creature_WebGL/tree/Phase3_5_Alpha/Phaser3

You can try it out, however it is currently not working. ( unfortunately ). I have managed to make the errors go away but for whatever reason, nothing seems to be rendering.

I have taken the time and filed an issue with Phaser officially here:
https://github.com/photonstorm/phaser/issues/5630

Please feel free to chime in and try out any suggestions on that issue I just filed. If Phaser can resolve it ( since this is their API and I do not understand what they changed given the fact Phaser 3.5 is a rather large change ), please follow their instructions on it. I will patch in the changes if you can possibly get some guidance from them on resolution of this issue.

Thanks

**Comment by diruuu** [comment]
Hi thank you very much. I'll monitor the issue.

**Comment by kestrelm** [comment]
I think I fixed it:
https://github.com/kestrelm/Creature_WebGL/commit/1950f908e79b0a31f596581af9d69bf4b3a4bd4c

Just checked into Master. The API has also slightly changed so please see how it is called in the new code. I am not quite sure if the new Phaser 3.5 API is stable yet so I had to take an alternate route. **CreaturePackObj** is no longer a regular Game Object but instead instantiates a new Phaser 3.5 Mesh class and keeps a reference to it ( you access it via CreaturePackObj.mesh ). You also need to remember to call tick() for each update. I am leaving the question on for Phaser devs to answer in case there is a better way to solve this issue with their new framework.

Thanks

**Comment by diruuu** [comment]
Sent you a PR #16 to remove the need to call tick() for each update. By using E6 class I'm able to call the preUpdate method of Phaser.GameObjects.Mesh

**Comment by kestrelm** [comment]
Awesome thanks! Merged.
