### ISSUE TITLE
Phaser demo is lose file

### ISSUE THREAD

**Issue by supermrji** [kestrelm/Creature_WebGL#2]
Can you provide some Creature file from json for Phaser v2.6
now can not running

**Comment by kestrelm** [comment]
Hello,

You can grab a sample JSON file here:
https://github.com/kestrelm/Creature_WebGL/blob/master/iceDemonExport_character_data.json

The texture atlas is here:
https://github.com/kestrelm/Creature_WebGL/blob/master/iceDemonExport_character_img.png

Cheers

**Comment by supermrji** [comment]
Thanks
