### ISSUE TITLE
Creature for EaselJS

### ISSUE THREAD

**Issue by rafelsanso** [kestrelm/Creature_WebGL#5]
Hi all!

I'm starting with HTML5 integrations. Specifically, I started with EaselJS. I have chosen this engine because it is very easy to import elements from Adobe Flash.
My question is whether you intend to export to this graphics engine. I tried to read the Phaser and Trree exporters, but I understand all the proccess to make my own runtime.

Best regards!

**Comment by kestrelm** [comment]
Hello,

I took at look at EasIJS:
http://www.createjs.com/docs/easeljs/modules/EaselJS.html

It does not seem to have WebGL or Mesh support. Creature is a mesh based animation system so I am not sure if this will run.

Cheers
