### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by aekiro** [kestrelm/Creature_WebGL#9]
should be this.data instead of data

https://github.com/kestrelm/Creature_WebGL/blob/360d279bdde2b091f65a392c927474470c7607ab/CreaturePackModule.js#L422

https://github.com/kestrelm/Creature_WebGL/blob/360d279bdde2b091f65a392c927474470c7607ab/CreaturePackModule.js#L423

**Comment by kestrelm** [comment]
Do you want to make a pull request for those 2 lines and I will merge them into the repository?

Thanks!

**Comment by kestrelm** [comment]
Never mind, this is fixed: 
https://github.com/kestrelm/Creature_WebGL/commit/8bd1fc5e7927afeb320f6707df0373d44b6be92a

Cheers
